# source 'https://github.com/CocoaPods/Specs.git'

# platform :ios, '15.0'

# use_frameworks!
# use_modular_headers!

# target 'Runner' do
#   platform :ios, '15.0'

#   use_frameworks!
#   use_modular_headers!

#   pod 'wireguard_flutter', :git => 'https://github.com/Caqil/wireguard_flutter'
#   pod 'path_provider_foundation', :git => 'https://github.com/flutter/packages'

# end